### ISSUE TITLE
Local filesystem support

### ISSUE THREAD

**Issue by michaelpeterlee** [marcklei/react-pdfjs-multi#26]
I played to extend PdfMultiViewer to support local files via Uint8Array(), can't remember what I changed it was so long ago in-between projects.

I looked to extend PdfRenderer but it won't play due to .autoFitScale() not having any items in _pages array. I'm not going to progress any further, but thought I'd share that adventure.

Q. Do you have any inclination to extend PdfRenderer for local files via Uint8Array() ?

**Comment by michaelpeterlee** [comment]
I got both components to work. My error with PdfRenderer was elementary, I did not pass the result from PdfjsLib.getDocument()

**Comment by marcklei** [comment]
Good job, I am glad to hear this. :)
